---
title: "Final Project Basic Outline"
author: "Mia and Madeline"
output: html_notebook
---

This is an outline for your final project. You can follow this outline, or you can modify it as you see fit. Do what works best for your project. 

## Research Question 

Our project delves into the question of whether there is a correlation between climate and population movement for different countries. When considering all possible reasons as to why people choose to live in certain locations, it is important to consider all contributing factors-- sunshine, tourism, latitude being a few. Seasonal depression and mood-changes based off the weather is a serious impact on many peoples' lives. Applying this knowledge, climate could be associated with certain locations having an increase in population and tourism over time. 



## Data Processing 

#### Data Intake 

Include R code and written explanation to import your **TWO** data sets.

#### Data Wrangling 

Include R code and written explanation for wangling your data (you can make multiple wrangled data sets). 




## Data Visualization

Include R code and written explanation for your data visualization(s) with at least 3 variables. You must have **at least** one graph. You may have more than one (I would encourage you to have more than one). 




## Conclusion

Answer your research question using the data sets and visualizations you created. 