---
title: "Initial EDA Basic Outline"
author: "Mia and Madeline"
output: html_notebook
---

This is an outline for your Initial EDA. You can follow this outline, or you can modify it as you see fit. Do what works best for your project. 

## Research Question 

Our project delves into the question of whether there is a correlation between sunshine and population and population growth rates. When considering all possible reasons as to why people choose to live in certain locations, it is important to consider all contributing factors-- sunshine being one. Seasonal depression and mood-changes based off the weather is a serious impact on many peoples' lives. Applying this knowledge, sunshine could be associated with certain locations having an increase in population over time. 


## Data Processing 

#### Data Intake 

Include R code and written explanation to import your **TWO** data sets.

library(tidyverse)

CityPopulations <- read_csv(file = "/Users/miaiceland/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/Stat-184/world-city-listing.csv")


#### Data Wrangling 

Include R code and written explanation for wrangling your data (you can make multiple wrangled data sets). 

CityPopulations1 <-
  CityPopulations %>%
    mutate(Country = country, City = city, Population2023 = pop2023, GrowthRate = growthRate) %>%
    select(Country, City, Population2023, GrowthRate) %>%
    filter() #choose which cities we want to evaluate


## Data Visualization

#### Plot 1

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 

#### Plot 2

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 


## Conclusion

Include your initial intuition as to what the answer to your research question is using the data sets and visualizations you created. 